### ISSUE TITLE
... in matches

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/tidyselect#58]
currently matches only passes the `ignore.case` parameter to `grep_vars`. Perhaps it would make sense to pass `...` as well. 

Would be interesting at least for arguments `perl`, `invert` and `fixed`

Alternatively, should this use `stringr` regexes ?

originally in https://github.com/tidyverse/dplyr/issues/3209

**Comment by mungojam** [comment]
Yes please to stringr matches. Once you are in the tidyverse you expect it to be consistent

**Comment by lionel-** [comment]
The problem is that it would mean depending on stringr and then on stringi and tidyselect should have light dependencies.

**Comment by lionel-** [comment]
cc @hadley

**Comment by romainfrancois** [comment]
maybe that can happen the other way and `stringr` can offer its version of matches and friends

**Comment by mungojam** [comment]
string manipulation feels like a lower level more cross cutting concern than tidyselect functionality, but I understand the desire to minimise dependencies

**Comment by lionel-** [comment]
stringi is a very heavy dependency (which for instance dplyr doesn't currently depend on AFAICT).

**Comment by hadley** [comment]
We can not can add `...` (because that locks into the interface for a specific regular expression library) and we can not add a stringr dependency (because stringi is a heavy dependency). tidyselect provides simpler helpers - if you need more complex regular expressions I think you should be handling it elsewhere.
